### ISSUE TITLE
Flaw in concept

### ISSUE THREAD

**Issue by Mecanik** [klezVirus/SysWhisper3#4]
I starred your repo because your idea is nice, however because you are using ReadProcessMemory which is a user mode function (in fact any API called...), you already lost.

Besides this you should use a SEED like PRNG or something.

Good idea again, but you should rework it a bit.

**Comment by klezVirus** [comment]
Hi @Mecanik, thanks a lot for reaching out, feedback is always critical to improve a project. However, I have a few questions: 
1. We are not using `ReadProcessMemory` anymore? What am I missing?
2. A seed? I'm not sure what you mean by that, we are already seeding the hasing function, so you're referring to the Egg generator? I discarded the idea of the PRNG because it can create patterns that are already in memory, do you have any evidence that implementing it as a PRNG would have some benefits over the current implementation?

**Comment by klezVirus** [comment]
Ok, the only point where `ReadProcessMemory` appears is in `example-output`, where I can also see the static seed used for the hashing algorithm. Probably it is not clear enough, so let me explain: `example-output` is just a directory that shows an example of the output provided by the tool. Even if we try, some updates to the main tool logic might not be reflected in this directory. That said, let me reformulate the answers to your questions:
1. The SEED is already generated RANDOMLY by SysWhispers3
2. `ReadProcessMemory` is not used anymore, but you can find it in `example-output` as we didn't update the examples after removing it from the codebase. What I'm saying by that is that the example output is not reflecting the current output of the tool.

If you want to check the current implementation, the best way for you is generating the stubs with all techs and take a look. I will now remove the example output directory because at this point I think it's only misleading.

Thanks for opening an issue, as you convinced me to get rid of that directory. As a general best practice, though, I would really recommend you taking a bit of time to truly understand the code you're looking at before jumping to conclusions.

Closing this now as invalid.

**Comment by Mecanik** [comment]
Ok, first of all, me, a wondering user, how am I supposed to know that a 2 months old commit is not "up to date"?

Second, this was pure positive criticism and nothing else. You should learn to take this from people as a positive thing and not jump up and tell me to "read your code".

Third, I have read your code and even cloned it. You still have flaws whether you want to accept it or not, and these include:

- Usage of rand() which can be traced easily, instead once again I give you some advice... https://prng.di.unimi.it/
- Usage of static array (even with the exact count) which shows a reverser where all the sys-calls are (pointer to array lol)

So take this as you want, I was just trying to help you. Honestly I won't bother anymore so good luck.

**Comment by klezVirus** [comment]
Hi @Mecanik, first thing, I'm sorry that you felt attacked by my comment, maybe I didn't explain myself good enough. I really appreciate what you're doing, and I apologised that the `example-output` directory was indeed, not reflecting the latest code. Indeed, based on your comment, I decided to delete the whole directory, as it is actually misleading.

I didn't want to offend you, even when I said you to better look at the code, I said it just because your comment was pointing to something which is not in the code anymore, making your suggestion pointless. This is surely because of the `example-output` issue, but I'm sure you can agree with me that before opening an issue, it's better to be sure the issue exists, otherwise, you should expect some complaints back.

That said, I gladly accept any suggestions or critiques that may contribute in making the tool better. Now, after the big intro, let's come to the flaws you've identified. 

1. Usage of rand(): Python hardly offers any function that permits to generate "TRUE random" numbers. I might change the implementation using `random.SystemRandom` or the secret module. Based on your feedback, I will surely look into that, but implementing a TRUE random generator in Python is really outside of the scope of this tool, I am afraid.
2. Usage of static array: the static array you're referring to is probably the linked list that stores the addresses of the syscalls, but regardless, you're right. A reverser executing the generated payload can detect the structure and extracts the addresses after `PopulateSyscalls()` has been called. I would argue that this tool was not designed to offer any anti-reversing capabilities, but having that would not be bad at all. I think that refactoring the code to get rid of these structures would not be effortless at all, but I'll have a look to what can be done in this sense. 

If you have any additional suggestions about the tool, you can also reach me out on discord:  klezVirus#4367.
